### ISSUE TITLE
RC4 Encryption possible migration

### ISSUE THREAD

**Issue by Nischay-Pro** [nsurampu/File_locker#2]
Though RC4 is a good solution to encryption and encrypting files several research papers have been published highlighting its insecurities. I'd recommend migrating to new stream cipher.

**Comment by nsurampu** [comment]
I just checked out on a few websites and it seems AES is a good encryption technique. I'll start work on it and upload the new code when completed

**Comment by nsurampu** [comment]
I have completed the switch from RC4 to AES encryption
